version: "2"
services:

  notecard:
    #image: bh.cr/tj/balena-notecard
    image: bhcr.io/tj/balena-notecard
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    ports:
      - 8080:8080
    privileged: true

  pool-tank:
    build: ./src
    privileged: true
    restart: always
    labels:
            io.balena.features.dbus: '1'
            io.balena.features.kernel-modules: '1'
    volumes: 
            - 'shared-data:/var/data'
            - 'shared-media:/var/media'
    environment:
            - UDEV=1
    devices:
            - '/dev:/dev'

volumes:
        shared-data:
        shared-media: